trigger:
  paths:
    include:
      - frontend/**

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'dockerhub_connection'  # ⬅ Change if needed
  imageRepository: 'atheerserver/three-tier-assignment-frontend.atheerfaisal.alqannas'               # ⬅ Change to frontend image repository
  vmConnection: 'vm-ssh-connection'                        # ⬅ Same as backend

stages:
- stage: BuildTest
  jobs:
  - job: BuildAndTest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        cd frontend
        npm install
        npm test
      displayName: 'Install & Test Frontend'

- stage: DockerBuildAndPush
  dependsOn: BuildTest
  jobs:
  - job: Dockerize
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: buildAndPush
        Dockerfile: Dockerfile
        tags: latest

- stage: Deploy
  dependsOn: DockerBuildAndPush
  jobs:
  - deployment: DeployToVM
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SSH@0
            inputs:
              sshEndpoint: $(vmConnection)
              runOptions: 'inline'
              inline: |
                # Stop and remove existing container if it exists
                docker ps -a | grep -q frontend && docker stop frontend && docker rm frontend || true
                # Pull the latest image
                docker pull $(imageRepository):latest
                # Run the new container
                docker run -d -p 3000:3000 --name frontend $(imageRepository):latest

